---
- name: "Install emacs"
  apt: pkg="emacs" state="present"

- name: "Install xsel."
  apt: pkg="xsel" state="present"

- name: "Install dependences via pip."
  command: pip install {{ item }}
  with_items:
    - cpplint # Code lint(cpp).
    - flake8 # Code lint(python
    # Pylint always make confusing error report about extern library. So I
    # switch to flake8.
    # - pylint # Code lint(python).
    - virtualenv # Jedi(python)
    - rope # ropemacs(python)
    - ropemacs # ropemacs(python)

  # This does not work. All ruby related stuff does not work with
  # ansible for the time being.
# - name: "Install robe dependences."
#   sudo: no
#   command: gem install pry
