---
- name: "Install .bashrc"
  copy: src=".bashrc" dest="~/.bashrc"

- name: "Install .tmux.conf"
  copy: src=".tmux.conf" dest="~/.tmux.conf"

- name: "Git clone vim config"
  git: repo=https://github.com/shawnLeeZX/.vim dest=~/.vim accept_hostkey=true

- name: "Install gitconfig"
  copy: src="gitconfig" dest="~/.gitconfig"

- name: "Install gitignore"
  copy: src="gitignore" dest="~/.gitignore"

- name: "Install useful scripts"
  copy: src="bin" dest="~/mine/"

- name: "Make scripts executable"
  shell: chmod 744 ~/mine/bin/*

- name: "Git clone emacs config"
  git: repo=https://github.com/shawnLeeZX/emacs.d dest=~/.emacs.d accept_hostkey=true
