---
- name: "Install tmux locally."
  script: tmux.sh

- name: "Install miniconda locally."
  script: miniconda.sh

- name: "Install tensorflow locally."
  # Note that this is for tensorflow 0.7.1. If a older version is needed, it
  # needs to be installed manually.
  script: tensorflow.sh

- name: "Install common libraries for python."
  script: py_pkgs.sh

- name: "Install common libraries for python."
  script: pycuda.sh

- name: "Install unison."
  script: unison.sh
