---
- name: "Change the sources.list"
  copy: src="sources.list" dest="/etc/apt/sources.list" force=yes

- name: "Change and source.list.d"
  copy: src="sources.list.d/" dest="/etc/apt/sources.list.d" force=yes

- name: "Install apt-keys"
  copy: src="trusted.gpg" dest="/etc/apt/" force=yes

- name: "Update apt cache"
  apt: update_cache=yes

- name: "Install aptitude"
  apt: pkg=aptitude state=present

- name: "Upgrade system"
  apt: upgrade=yes

# Install necessary libraries for compiling vim.
- name: "Install xorg-dev. This package enable X11 related feautre of vim"
  apt: pkg=libncurses5-dev state=present

- name: "Install libncurses"
  apt: pkg=libncurses5-dev state=present

- name: "Install python2.7-dev"
  apt: pkg=python2.7-dev state=present

- name: "Install lua5.2"
  apt: pkg=lua5.2 state=present

- name: "Install liblua5.2"
  apt: pkg=liblua5.2-dev state=present

- name: "Install perl library"
  apt: pkg=libperl-dev state=present

- name: "Install tcl library"
  apt: pkg=tcl-dev state=present

- name: "Install ruby library"
  apt: pkg=ruby-dev state=present

# Install necessary softwares.
- name: "Install git"
  apt: pkg=git state=present

- name: "Install cscope"
  apt: pkg="cscope" state=present

- name: "Install ctags"
  apt: pkg="ctags" state=present

- name: "Install tmux"
  apt: pkg=tmux state=present

- name: "Install w3m"
  apt: pkg=w3m state=present

- name: "Install tree"
  apt: pkg=tree state=present

# Install self-compiled vim74.
- name: "Copy compiled vim tarball"
  copy: src="vim74.tar.gz" dest="/tmp"

- name: "Install vim in /usr/local/bin and make it system default."
  script: install_vim.sh

- name: "Upgrade gcc/g++ to 4.8"
  apt: pkg="g++-4.8" state=present

- name: "Make gcc/g++ 4.8 the default version"
  command: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8

# For using minted for latex.
- name: "Install pygmentize"
  apt: pkg="python-pygments" state=present
